syntax = "proto3";

package beget.promo.v1.ny2027;
import "google/api/annotations.proto";

service Ny2027Service {
  // Получить выполненные задания
  rpc getExerciseCompleted (GetExerciseCompletedRequest) returns (GetExerciseCompletedResponse) {
    option (google.api.http) = {
      get: "/v1/promo/ny2027/exercise-completed"
    };
  }

  // Отправить результат на проверку
  rpc submitExercise (SubmitExerciseRequest) returns (SubmitExerciseResponse) {
    option (google.api.http) = {
      post: "/v1/promo/ny2027/submit-exercise"
      body: "*"
    };
  }
}

message GetExerciseCompletedRequest {}

message GetExerciseCompletedResponse {
  repeated Exercise exercise = 1;
  message Exercise {
    ExerciseType exercise_type = 1;
  }
}

message SubmitExerciseRequest {
  ExerciseType exercise_type = 1;
  // Сервер (compute)
  ServerComputeConfig server_compute = 2;
  // Сетевые диски (SSD)
  NetworkDiskConfig network_disk = 3;
  // S3
  S3Config s3 = 4;
  // DBaaS
  DBaaSConfig dbaas = 5;
  // Канал связи
  BandwidthConfig bandwidth = 6;
  // CDN
  CDNConfig cdn = 7;
  // IPv6
  IPv6Config ipv6 = 8;
  // Бэкапы
  BackupsConfig backups = 9;
  // VPN/Приватная сеть
  VPNConfig vpn = 10;
}

message ServerComputeConfig {
  uint32 cpu_cores = 1;
  uint32 ram_gb = 2;
}

message NetworkDiskConfig {
  uint32 volume_gb = 1;
}

message S3Config {
  uint32 volume_gb = 1;
}

message DBaaSConfig {
  DBaaSSize size = 1;
}

message BandwidthConfig {
  uint32 bandwidth_mbps = 1;
}

message CDNConfig {
  uint32 bandwidth_mbps = 1;
}

message IPv6Config {}

message BackupsConfig {}

message VPNConfig {}

message SubmitExerciseResponse {
  oneof result {
    Success success = 1;
    ComponentErrors component_errors = 2;
    Ddos ddos = 3;
  }

  message Success {}

  message ComponentErrors {
    repeated ComponentError errors = 1;
  }

  message ComponentError {
    ComponentType component_type = 1;
    string message = 2;
  }

  message Ddos {
    string message = 1;
  }
}

enum ExerciseType {
  SCENARIO_TYPE_UNSPECIFIED = 0;
  SCENARIO_TYPE_ONLINE_LEARNING_PLATFORM = 1;   // Платформа онлайн-обучения
  SCENARIO_TYPE_ECOMMERCE_SALE = 2;             // Распродажа: highload-магазин
  SCENARIO_TYPE_INTERNAL_PORTAL_CRM = 3;        // Внутренний портал / CRM
  SCENARIO_TYPE_VIDEO_STREAMING_SERVICE = 4;    // Видеостриминговый сервис
  SCENARIO_TYPE_MOBILE_APP_BACKEND = 5;         // Backend мобильного приложения
}

enum ComponentType {
  COMPONENT_TYPE_UNSPECIFIED = 0;
  COMPONENT_TYPE_SERVER_COMPUTE = 1;          // Сервер (compute)
  COMPONENT_TYPE_NETWORK_DISK_SSD = 2;        // Сетевые диски (SSD)
  COMPONENT_TYPE_S3 = 3;                      // S3
  COMPONENT_TYPE_DBAAS = 4;                   // DBaaS
  COMPONENT_TYPE_BANDWIDTH = 5;               // Канал связи
  COMPONENT_TYPE_CDN = 6;                     // CDN
  COMPONENT_TYPE_IPV6 = 7;                    // IPv6
  COMPONENT_TYPE_BACKUPS = 8;                 // Бэкапы
  COMPONENT_TYPE_VPN_PRIVATE_NETWORK = 9;     // VPN/Приватная сеть
}

enum DBaaSSize {
  DBAAS_SIZE_UNSPECIFIED = 0;
  DBAAS_SIZE_SMALL = 1;
  DBAAS_SIZE_MEDIUM = 2;
  DBAAS_SIZE_LARGE = 3;
}