syntax = "proto3";

package beget.promo.v1.signupCashback2025;
import "google/api/annotations.proto";

// Промо-кешбек за переход по ссылке
//
// Предоставляет метод активации акции начисления кешбека на первое пополнение баланса
// при переходе пользователя в панель управления по промо-ссылке.
service SignupCashback2025Service {
  // Активировать участие в акции
  //
  // Активирует акцию для текущего авторизованного пользователя. Кешбек будет начислен
  // на первое пополнение баланса реальными деньгами за всю историю аккаунта.
  //
  // Активация отклоняется, если пользователь уже пополнял баланс ранее, либо если по номеру
  // телефона или email, привязанным к аккаунту, в акции уже участвует другой аккаунт.
  rpc activate (ActivateRequest) returns (ActivateResponse) {
    option (google.api.http) = {
      post: "/v1/promo/signupcashback2025/activate"
      body: "*"
    };
  }
}

message ActivateRequest {
  // Значение GET-параметра bonus из промо-ссылки
  int32 bonus = 1;
}

message ActivateResponse {
  // Результат запроса
  oneof result {
    // Результат запроса: акция успешно активирована
    Success success = 1;

    // Результат запроса: произошла ошибка при активации
    Error error = 2;
  }

  message Success {}

  // Ошибка активации промо
  message Error {
    // Код ошибки
    Code code = 1;

    // Сообщение об ошибке
    string message = 2;

    // Код ошибки активации промо.
    enum Code {
      // Значение по умолчанию.
      _ = 0;

      // Пользователь уже пополнял баланс ранее
      HAS_PAYMENTS = 1;
      // Пользователь с таким номером телефона или email уже участвует в акции
      CONTACT_ALREADY_PARTICIPATED = 2;
    }
  }
}